services:
  - type: web
    name: display-difference-checker-supratimbiswas
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium && python -m playwright install-deps chromium
    startCommand: gunicorn app:app --workers 2 --timeout 300 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
